#!/bin/bash

echo "🚀 Deploying with Database Connection Fix"
echo "========================================="

echo "✅ Applied fixes:"
echo "1. Added database connection environment variables to render.yaml"
echo "2. Connected backend service to managed database 'hp-printer-db'"
echo "3. Database credentials will be automatically provided by Render"

echo ""
echo "📋 Current configuration:"
echo "- Backend service connects to managed database"
echo "- Database credentials auto-generated by Render"
echo "- Database connection variables:"
echo "  - DB_HOST (from database)"
echo "  - DB_USER (from database)"
echo "  - DB_PASSWORD (from database)"
echo "  - DB_NAME (from database)"
echo "  - DB_PORT (from database)"

echo ""
echo "🚀 Deploying to Render..."

# Add all changes
git add .

# Commit with descriptive message
git commit -m "Fix database connection for Render deployment

- Added database connection environment variables to render.yaml
- Connected backend service to managed database 'hp-printer-db'
- Database credentials automatically provided by Render
- Resolves 'connect ECONNREFUSED ::1:3306' error
- Backend will now connect to managed PostgreSQL database"

echo ""
echo "📦 Pushing to GitHub..."

# Push to main branch
git push origin main

echo ""
echo "✅ Deployment initiated!"
echo ""
echo "🔍 Monitor your deployment:"
echo "1. Go to: https://dashboard.render.com"
echo "2. Check your service status"
echo "3. View build logs"
echo ""
echo "📊 Database will be automatically created by Render"
echo "🧪 Test your deployment:"
echo "Health check: https://your-service.onrender.com/health"
echo "API base: https://your-service.onrender.com/api"
echo ""
echo "🎉 This should resolve the database connection error!"
